language: ruby
services: memcache
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
matrix:
  allow_failures:
    - env: "AS_VERSION=master"
env:
  - "AS_VERSION=3.2.16"
  - "AS_VERSION=4.0.2"
  - "AS_VERSION=master"
