name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        entry:
          - name: 'Minimum supported'
            ruby: '2.6'
            gemfile: "Gemfile.min"
          - name: 'Latest released'
            ruby: '3.0'
            gemfile: "Gemfile"
          - name: 'Rails edge'
            ruby: '3.1'
            gemfile: "Gemfile.edge"

    name: ${{ matrix.entry.name }}

    env:
      BUNDLE_GEMFILE: ${{ matrix.entry.gemfile }}

    services:
      memcached:
        image: memcached
        ports:
          - 11211:11211

    steps:
    - run: sudo apt-get -y install libsasl2-dev
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - uses: ruby/setup-ruby@e34163cd15f4bb403dcd72d98e295997e6a55798 # v1.238.0
      with:
        ruby-version: ${{ matrix.entry.ruby }}
        rubygems: '3.3.13'
        bundler-cache: true
    - run: bundle exec rake
