name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        entry:
          - ruby: '2.7'
          - ruby: '3.0'

    name: "Ruby ${{ matrix.entry.ruby }}"

    services:
      memcached:
        image: memcached
        ports:
          - 11211:11211

    steps:
    - run: sudo apt-get -y install libsasl2-dev
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.entry.ruby }}
        bundler-cache: true
    - run: bundle exec rake
