name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        entry:
          - name: 'Minimum supported'
            ruby: '2.6'
            gemfile: "Gemfile.min"
          - name: 'Latest released'
            ruby: '3.0'
            gemfile: "Gemfile"
          - name: 'Rails edge'
            ruby: '3.1'
            gemfile: "Gemfile.edge"

    name: ${{ matrix.entry.name }}

    env:
      BUNDLE_GEMFILE: ${{ matrix.entry.gemfile }}

    services:
      memcached:
        image: memcached
        ports:
          - 11211:11211

    steps:
    - run: sudo apt-get -y install libsasl2-dev
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ruby/setup-ruby@65937904bcddfb93f8130882d9afa8597c45f3b5 # v1.249.0
      with:
        ruby-version: ${{ matrix.entry.ruby }}
        rubygems: '3.3.13'
        bundler-cache: true
    - run: bundle exec rake
