name: CI
on:
  push: {}
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        entry:
          - name: 'Minimum supported'
            ruby: '2.6'
            gemfile: "Gemfile.min"
          - name: 'Latest released'
            ruby: '3.4'
            gemfile: "Gemfile"
          - name: 'Rails edge'
            ruby: '3.4'
            gemfile: "Gemfile.edge"

    name: ${{ matrix.entry.name }}

    env:
      BUNDLE_GEMFILE: ${{ matrix.entry.gemfile }}

    services:
      memcached:
        image: memcached
        ports:
          - 11211:11211

    steps:
    - run: sudo apt-get -y install libsasl2-dev libmemcached-dev
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ruby/setup-ruby@2a7b30092b0caf9c046252510f9273b4875f3db9 # v1.254.0
      with:
        ruby-version: ${{ matrix.entry.ruby }}
        rubygems: '3.3.13'
        bundler-cache: true
    - run: bundle exec rake
